# Generated by Django 2.1.5 on 2019-03-14 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Aviso',
            },
        ),
        migrations.CreateModel(
            name='AvisoViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizado', models.DateTimeField(blank=True, help_text='Is set when user sees the warning in details', null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.Aviso')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_visualizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aviso',
            name='viewers',
            field=models.ManyToManyField(through='avisos.AvisoViewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='avisoviewer',
            unique_together={('aviso', 'viewer')},
        ),
    ]
