# Generated by Django 2.1.5 on 2019-03-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avisoviewer',
            table='Aviso_viewer',
        ),
    ]
