# Generated by Django 2.1.5 on 2019-03-14 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avisos', '0002_auto_20190314_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avisoviewer',
            old_name='viewer',
            new_name='residente',
        ),
        migrations.AlterUniqueTogether(
            name='avisoviewer',
            unique_together={('aviso', 'residente')},
        ),
    ]
