# Generated by Django 2.1.5 on 2019-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0004_auto_20190314_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='subtítulo'),
        ),
    ]
