# Generated by Django 2.1.5 on 2019-03-20 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avisos', '0005_auto_20190319_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='editado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos_editado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='viewers',
            field=models.ManyToManyField(related_name='avisos_viewers', through='avisos.AvisoViewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avisoviewer',
            name='data_visualizado',
            field=models.DateTimeField(blank=True, help_text='Esse campo é populado quando o usuário clica em "Ler mais" no aviso.', null=True),
        ),
    ]
