# Generated by Django 2.1.3 on 2018-11-15 21:57

import contas.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('C', 'Caseiro'), ('F', 'Funcionário'), ('P', 'Proprietário')], default='P', max_length=1)),
                ('token', models.CharField(default=contas.models.token_generator, max_length=8, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ],
            options={
                'db_table': 'Residente',
            },
        ),
        migrations.CreateModel(
            name='Chacara',
            fields=[
                ('id', models.AutoField(db_column='chac_ID', primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=15)),
                ('via', models.CharField(max_length=25)),
                ('lote', models.CharField(max_length=10)),
                ('quadra', models.CharField(max_length=6)),
                ('classe', models.CharField(max_length=6)),
                ('operacao', models.IntegerField()),
            ],
            options={
                'verbose_name': 'chácara',
                'verbose_name_plural': 'chácaras',
                'db_table': 'Chacara',
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(db_column='mov_ID', primary_key=True, serialize=False)),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('aberto', models.IntegerField()),
                ('aberport_id', models.SmallIntegerField()),
                ('fechport_id', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Movimento',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(db_column='vis_ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nomevis', max_length=50)),
                ('veiculo', models.CharField(db_column='veic_ID', max_length=7, null=True)),
                ('nomeres', models.CharField(db_column='nomeres', default='DESCONHECIDO', max_length=50)),
                ('oculto', models.BooleanField(db_column='Oculto', default=False)),
                ('blacklist', models.BooleanField(db_column='Blacklist', default=False)),
                ('chacara', models.ForeignKey(db_column='chac_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='visitantes', to='contas.Chacara', verbose_name='chácara')),
            ],
            options={
                'db_table': 'Visitante',
            },
        ),
        migrations.AddField(
            model_name='movimento',
            name='visitante',
            field=models.ForeignKey(db_column='vis_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Visitante', verbose_name='visitante'),
        ),
        migrations.AddField(
            model_name='residente',
            name='chacara',
            field=models.ForeignKey(db_column='chac_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='residentes', to='contas.Chacara', verbose_name='chácara'),
        ),
        migrations.AddField(
            model_name='residente',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='residente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='residente',
            unique_together={('chacara', 'nome')},
        ),
    ]
