# Generated by Django 2.1.3 on 2018-11-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20181115_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='agendado',
            field=models.BooleanField(db_column='Agendado', default=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
