# Generated by Django 2.1.3 on 2018-12-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20181115_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='visitante',
            field=models.ForeignKey(db_column='vis_ID', on_delete=django.db.models.deletion.PROTECT, to='contas.Visitante', verbose_name='visitante'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='chacara',
            field=models.ForeignKey(db_column='chac_id', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residentes', to='contas.Chacara', verbose_name='chácara'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='chacara',
            field=models.ForeignKey(db_column='chac_ID', on_delete=django.db.models.deletion.PROTECT, related_name='visitantes', to='contas.Chacara', verbose_name='chácara'),
        ),
    ]
