# Generated by Django 2.1.5 on 2019-03-20 02:48

import contas.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_auto_20190319_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chacara',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=contas.storage.OverwriteStorage(), upload_to=contas.storage.update_filename),
        ),
    ]
