# Generated by Django 2.1.5 on 2019-03-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_auto_20190319_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chacara',
            options={'ordering': ['id'], 'verbose_name': 'chácara', 'verbose_name_plural': 'chácaras'},
        ),
    ]
